apiVersion: batch/v1
kind: Job
metadata:
  name: media-optimizer-job
spec:
  backoffLimit: 0 # We want it to fail fast if there's a code error
  template:
    spec:
      containers:
      - name: media-optimizer-container
        image: media-optimizer:latest
        imagePullPolicy: Never 
        env:
          - name: PR_NUMBER
            value: "${PR_NUMBER}" # Injected by GitHub Actions
          - name: MONGO_URI
            value: "mongodb://mongodb-service:27017/media-db"
        volumeMounts:
        - name: project-root
          # MUST be /app to match your optimize.js script
          mountPath: /app 
      volumes:
      - name: project-root
        hostPath:
          # Use the absolute path to your repo on your Ubuntu laptop
          path: /home/nadeem/msrit/media-optimization-pipeline 
          type: Directory
      restartPolicy: Never