apiVersion: batch/v1
kind: Job
metadata:
  name: media-optimizer-job
  labels:
    app: media-optimizer
spec:
  # How many retries if the job fails
  backoffLimit: 2 
  template:
    spec:
      containers:
      - name: media-optimizer-container
        image: media-optimizer:latest
        # This tells K8s to use your local Docker image
        imagePullPolicy: Never 
        volumeMounts:
        - name: asset-volume
          mountPath: /sample-assets
      volumes:
      - name: asset-volume
        hostPath:
          # THIS IS THE FIX: We use the bridge path now!
          path: /sample-assets
          type: Directory
      restartPolicy: Never